### ISSUE TITLE
PowerShell Error

### ISSUE THREAD

**Issue by dstanley3** [MysticRyuujin/PlexMissingEpisodes#4]
Failed to get TheTVDB API Token:
The term 'Invoke-RestMethod' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by MysticRyuujin** [comment]
You either have an issue with your PowerShell or you're running an old version of PowerShell

IRM was introduced in PowerShell 3.0

You can run `$PSVersionTable` to get your PowerShell version number - if you're on Windows you can upgrade PowerShell by upgrading the WMF.

If you're on Linux running PS Core - then let me know because I'm pretty sure that it exists over there...

**Comment by dstanley3** [comment]
Old version of PowerShell.  Updating now.  Thanks for the fast response!
